### ISSUE TITLE
6. Base tests

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/twpm-docs#21]
For testing of the implementation done so far, a subset of tpm2-tools commands will be used. Only commands that do not depend on Protected Storage, RNG and Primary Keys Certificates will be tested at this point.

Milestone:

- [x] test suite: PCR operations (read, extend, reset values, locality protection)
- [x] test suite: object creation (primary, ordinary, derived objects of various types)
- [x] test suite: cryptographic support functions (hash, HMAC, encryption, signing)
- [x] documentation of results
- [x] review and update existing documentation, add entry to changelog

**Comment by krystian-hebel** [comment]
All tests were migrated as part of https://github.com/Dasharo/open-source-firmware-validation/pull/8 except for locality protection check, which was implemented in https://github.com/Dasharo/open-source-firmware-validation/pull/111.

**Comment by BeataZdunczyk** [comment]
Closing this issue as all requirements have been met.

- Documentation of results can be found here: https://twpm.dasharo.com/development/testing/
- Test results are available here: https://twpm.dasharo.com/test-results/2024_01_11_orange_crab_without_create_primary.html
- The updated changelog is located here: https://twpm.dasharo.com/changelog/#2024-01-16

**Comment by BeataZdunczyk** [comment]
If someone is curious about the details of our TwPM testing, we've shared additional insights in our [blog post](https://blog.3mdeb.com/2024/2024-01-31-twpm-testing/).
